go.property("from_y", 640)
go.property("to_y", -640)

go.property("offset", vmath.vector3())

function init(self)
	-- Let the starting position be somewhere on the screen
	self.y = self.from_y / 2

	self.enabled = false
end

function final(self)
end

function update(self, dt)
end

function fixed_update(self, dt)
	if not self.enabled then
		return
	end

	-- Infinite fall from the top to the bottom
	local diff = self.to_y - self.from_y
	self.y = self.y + diff * dt * 0.3
	if self.y < self.to_y then
		self.y = self.y - diff
	end

	local pos = vmath.vector3(0, self.y, 0) + self.offset
	go.set_position(pos)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("start") then
		self.enabled = true

		if message.offset then
			self.offset = message.offset
		end
	end
end

function on_input(self, action_id, action)
end

function on_reload(self)
end
